title: OpenPol.org
description: This is an Open source project aiming to provide tools for managing citywide police departments.
show_downloads: false
google_analytics: UA-166118961-1
theme: jekyll-theme-tactile